In [1]:
import numpy as np

In [10]:
np.full((2, 8, 8), False)

array([[[False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False]],

       [[False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        

In [5]:
np.array([2,3,9]).shape

(3,)

In [6]:
test = np.array([1,2,3])
test

array([1, 2, 3])

In [7]:
def foo(arr):
    return np.array([arr+1, arr+2])

In [8]:
foo(test)

array([[2, 3, 4],
       [3, 4, 5]])

In [9]:
test

array([1, 2, 3])

In [11]:
class GameState:
    ## walls is (2,8,8) vector where first 8x8 is horizontal walls and second 8x8 is vertical walls
    ## agents is (2, 3) vector
        ## agents[0] is white
        ## angets[1] is black
        ## agents[0][0] is white x coord (row)
        ## agents[0][1] is white y coord (col)
        ## agents[0][2] is walls white has left
        ## and vice versa
    def __init__(self, walls, agents):
        self.walls = walls
        self.agents = agents

    ## returns np.array of the possible game states reachable
    ## with a single move from this gamestate
    def possibleStates(self):
        return np.array([])

In [12]:
state = GameState(np.full((2, 8, 8), False), np.array([[4, 0, 10], [4, 8, 10]]))

In [13]:
state.walls

array([[[False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False]],

       [[False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        

In [14]:
class box:
    wall = '\033[41m  \033[0m'
    wallbg = '\033[43m  \033[0m'
    possible = '\033[44m  \033[0m'
    bg = '\033[46m  \033[0m'
    black = '\033[42m  \033[0m'
    white = '\033[47m  \033[0m'

In [18]:
box = ['\033[46m  \033[0m', '\033[41m  \033[0m', '\033[43m  \033[0m', '\033[44m  \033[0m', '\033[42m  \033[0m', '\033[47m  \033[0m']

bg = 0
wall = 1
wallbg = 2
possible = 3
black = 4
white = 5

In [17]:

1 * (3+1) * 9

36

In [22]:
b = np.zeros((36, 36), dtype=int)

In [23]:
# wall length is 7
# vertical wall goes 7 down
for row, arrRow in enumerate(state.walls[0]):
    for col, arrCol in enumerate(arrRow):
        if arrCol:
            for i in range(7):
                pixels[row+i, col] = wall
                
# horizontal wall goes 7 right
for row, arrRow in enumerate(state.walls[1]):
    for col, arrCol in enumerate(arrRow):
        if arrCol:
            for i in range(7):
                pixels[row, col+i] = wall

In [24]:
import re

In [28]:
not re.match(r'[vhm][0-9][0-9]', 'v23')

False

In [29]:
not re.match(r'[vhm][0-9][0-9]', 'a23')

True

In [30]:
np.array([1,3]) == np.array([1,3])

array([ True,  True])

In [32]:
np.array_equal(np.array([1,3]), np.array([1,3]))

True

In [33]:
np.array_equal(np.array([1,3]), np.array([1,2]))

False

In [34]:
b = False

In [35]:
arr = ['zero', 'one']

In [36]:
arr[b]

'zero'

In [37]:
'0' == '0'

True

In [38]:
'0' == 0

False

In [39]:
'0' == '1'

False

In [40]:
if 0:
    print(0)

In [41]:
if 1:
    print(0)

0


In [1]:
node = Dict()

NameError: name 'Dict' is not defined

In [2]:
node = dict()

In [3]:
node['row'] = 4

In [4]:
node

{'row': 4}

In [5]:
node.row

AttributeError: 'dict' object has no attribute 'row'

In [6]:
import numpy as np

class GameState:
    ## walls is (2,8,8) vector where first 8x8 is vertical walls and second 8x8 is horizontal walls
    ## agents is (2, 3) vector
        ## agents[0] is black
        ## angets[1] is white
        ## agents[1][0] is white y coord (row)
        ## agents[1][1] is white x coord (col)
        ## agents[1][2] is walls white has left
        ## and vice versa
    def __init__(self, walls, agents, turn = 1):
        self.walls = walls
        self.agents = agents
        self.turn = turn ## is it white's turn?

    ## returns np.array of the possible game states reachable
    ## with a single move from this gamestate
    def possibleStates(self):
        return np.array([])

    def __eq__(self, state):
        return np.array_equal(self.walls, state.walls) and np.array_equal(self.agents, state.agents) and self.turn == state.turn

    def copy(self):
        return GameState(self.walls.copy(), self.agents.copy(), self.turn)

    @classmethod
    def newGame(state):
        return GameState(np.full((2, 8, 8), False), np.array([[8, 4, 10], [0, 4, 10]]))

    def passTurn(self):
        self.turn = 1 - self.turn

    ## some helpers for the pathfinding
    ## start is np.array([row, col])
    # def checkLeft(self, start):
    def checkUp(self, row, col):
            ## can't be at the top row
            ## not blocked by wall above
            ## not blocked by wall left above
        return row != 0 and \
            (not self.walls[1, row - 1, col] if col < 8 else True) and \
            (not self.walls[1, row - 1, col - 1] if col > 0 else True)

    def checkDown(self, row, col):
            ## can't be at the top row
            ## not blocked by wall right below
            ## not blocked by wall left above
        return row != 8 and \
            (not self.walls[1, row, col] if col < 8 else True) and \
            (not self.walls[1, row, col-1] if col > 0 else True)

    def checkLeft(self, row, col):
            ## can't be at the leftmost col
            ## not blocked by wall right to left
            ## not blocked by wall left above
        return col != 0 and \
            (not self.walls[0, row, col - 1] if row < 8 else True) and \
            (not self.walls[0, row - 1, col - 1] if row > 0 else True)

    def checkRight(self, row, col):
            ## can't be at the rightmost col
            ## not blocked by wall right to right
            ## not blocked by wall right and above
        return col != 8 and \
            (not self.walls[0, row, col] if row < 8 else True) and \
            (not self.walls[0, row - 1, col] if row > 0 else True)


    ## returns a list of possible coordinates for the current player to move
    def possibleMoves(self):
        turn = self.turn
        row = self.agents[turn, 0]
        col = self.agents[turn, 1]
        oppRow = self.agents[1-turn, 0]
        oppCol = self.agents[1-turn, 1]
        output = []
        print(row, col)
        print(oppRow, oppCol)

        #### up ####
        if  self.checkUp(row, col):
            # blocked by opponent
            if oppCol == col and oppRow == row - 1:
                output += self.possibleMovesOver(0);
            else:
                state = self.copy()
                state.agents[turn, 0] = row - 1
                state.passTurn()
                output.append(state)

        #### down ####
        if  self.checkDown(row, col):  
            # blocked by opponent
            if oppCol == col and oppRow == row + 1:
                output += self.possibleMovesOver(1);
            else:
                state = self.copy()
                state.agents[turn, 0] = row + 1
                state.passTurn()
                output.append(state)

        #### left ####
        if  self.checkLeft(row, col):     
            # blocked by opponent
            if oppCol == col - 1 and oppRow == row:
                output += self.possibleMovesOver(2);
            else:
                state = self.copy()
                state.agents[turn, 1] = col - 1
                state.passTurn()
                output.append(state)

        #### right ####
        if  self.checkRight(row, col): \
            # blocked by opponent
            if oppCol == col + 1 and oppRow == row:
                output += self.possibleMovesOver(3);
            else:
                state = self.copy()
                state.agents[turn, 1] = col + 1
                state.passTurn()
                output.append(state)
        return output;

    ## helper function for possibeOver
    ## in case the two players are right next to each other
    ## and need to jump over one another
    def possibleMovesOver(self, pos):
        # pos 0 == up
        # pos 1 == down
        # pos 2 == left
        # pos 3 == right
        turn = 1 - self.turn
        row = self.agents[turn, 0]
        col = self.agents[turn, 1]
        output = []

        #### up ####
        if  pos != 1 and self.checkUp(row, col):
            state = self.copy()
            state.agents[1 - turn, 0] = row - 1
            state.agents[1 - turn, 1] = col
            state.passTurn()
            output.append(state)

        #### down ####
        if  pos != 0 and self.checkDown(row, col):  
            state = self.copy()
            state.agents[1 - turn, 0] = row + 1
            state.agents[1 - turn, 1] = col
            state.passTurn()
            output.append(state)

        #### left ####
        if  pos != 3 and self.checkLeft(row, col):     
            print("over left")
            state = self.copy()
            state.agents[1 - turn, 0] = row
            state.agents[1 - turn, 1] = col - 1
            state.passTurn()
            output.append(state)

        #### right ####
        if  pos != 2 and self.checkRight(row, col):
            print("over right")
            state = self.copy()
            state.agents[1 - turn, 0] = row
            state.agents[1 - turn, 1] = col + 1
            state.passTurn()
            output.append(state)
        return output;



In [7]:
abs(3-2)

1

In [8]:
abs(1-2)

1

In [9]:
if []:
    print(2)

In [11]:
if [2]:
    print(2)

2


In [12]:
import heapq

H = [21,1,45,78,3,5]
# Use heapify to rearrange the elements
heapq.heapify(H)
print(H)

[1, 3, 5, 78, 21, 45]


In [13]:
heapq.heappush(H,8)
print(H)

[1, 3, 5, 78, 21, 45, 8]


In [14]:
bool(H)

True

In [15]:
heapq.heappop(H)

1

In [16]:
heapq.heappop(H)

3

In [17]:
heapq.heappop(H)

5

In [18]:
heapq.heappop(H)

8

In [19]:
heapq.heappop(H)

21

In [20]:
heapq.heappop(H)

45

In [21]:
heapq.heappop(H)

78

In [22]:
print(H)

[]


In [23]:
bool(H)

False

In [28]:
## np.full((9,9), np.inf)

In [26]:
## meant to be used in the various A* derivatives
class Node:
    def __init__(self, row, col, fromStart, endRow = 0, endCol = 0, parent = None):
        self.row = row
        self.col = col
        self.fromStart = fromStart                      ## aka gScore
        self.toEnd = abs(endRow-row)+abs(endCol-col)    ## aka hScore
        self.parent = parent                            ## aka fScore

    ## so I can use heaps to pick the lowest fCost for the performance
    def __lt__(self, node):
        return self.fromStart + self.toEnd < node.fromStart + node.toEnd


In [27]:
np.full((3,3), Node)

array([[<class '__main__.Node'>, <class '__main__.Node'>,
        <class '__main__.Node'>],
       [<class '__main__.Node'>, <class '__main__.Node'>,
        <class '__main__.Node'>],
       [<class '__main__.Node'>, <class '__main__.Node'>,
        <class '__main__.Node'>]], dtype=object)

In [29]:
import random

In [31]:
random.getrandbits(10)

139

In [32]:
random.getrandbits(1)

0

In [1]:
np.inf

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [4]:
np.inf > 100

True

In [5]:
-np.inf

-inf